### ISSUE TITLE
rethinkdb://asgard.gamecult.games:28015

### ISSUE THREAD

**Issue by johndpope** [rwvens/aetherdb-ios#1]
how to get sample db?

**Comment by metacratic** [comment]
Sorry, I had to take that particular DB down after it got taken over by "hackers" and filled with mysterious garbage. Really, any instance of RethinkDB will work. You can easily run it on your own computer.

**Comment by johndpope** [comment]
Would you recommend rethink for a massive social network system? I’m currently using fire base but afraid of incoming costs

**Comment by metacratic** [comment]
I landed on Rethink specifically because I was looking for something similar to Firebase (especially the "real-time" features) which can be self-hosted. It's certainly possible to scale with it, as it supports clustered deployments and replication.

**Comment by johndpope** [comment]
Thx
